Regression analysis

Here comes a report of a regression analyses, which focuses on how attitude and three different learning styles affects the success in learning statisstics, assesed in points. The data was collected among students at the UH. After data management, the final dataset contained N = 166 participants. The average age of the participants was somewhat over 25 years; there were 110 female and 56 male participants.

The dependent variable I use the analysis is Points. Theindependent variables were deep, surface and strategic learning styles, and attitudes toward learning. Age and gender were used as control variables.

I performed some t-tests, correlational analyses to check the relevant bivariate relationships. Also, I visualized the bivariate relationsip between the theoretically relevant inndependent variables and points, and checked also how these relatinships differ between male and female students.

I performed at least a dozen regressions with IVs in different combinations and included even interaction terms, but as a matter of fact, none of the models was really interesting. This is pity because I thought that attitudes and learning styles would interact in predicting points... Also, after visualising the data, I expected that the effect of deep learning style on points is moderated by gender; however, it was not the case.

```{r}

library(readr)
learning14 <- read_csv("D:/IODS-project-2/learning14.csv")
View(learning14)
View(learning14)

str(learning14)
mean(learning14$Age)
str(learning14$gender)
View(learning14$gender)

library(ggplot2)

#I have created a couple of graphs with ggplot2. The first one has appeared to be interesting,
# but only at the first sight (I tested the combined effect of deep and gender on points, and
# it was not different from zero).

plot1a <- ggplot(learning14, aes(x=deep, y=Points, col = gender))
plot1b <- plot1a + geom_smooth(method = "lm")             
plot1b          

plot2a <- ggplot(learning14, aes(x=surf, y=Points, col = gender))
plot2b <- plot2a + geom_smooth(method = "lm")             
plot2b          

plot3a <- ggplot(learning14, aes(x=stra, y=Points, col = gender))
plot3b <- plot3a + geom_smooth(method = "lm")             
plot3b          

head(learning14)

# Also, I have performed a set of bivariate analyses to test the individual effects of
# age, gender and learning attitude on the outcome variable.

cor.test(learning14$Age, learning14$Points)
cor.test(learning14$Attitude, learning14$Points)
t.test(learning14$Points ~ learning14$gender)

#I performed at least a dozen regressions with IVs in different combinations and included
# interaction terms, but as a matter of fact, none of them was really interesting. This is pity
# because I thought that attitudes and learning styles would interact in predicting points... So I kept
# the following model, where attitude is defined as IV and the model is controlled for gender and age.

model <- lm(learning14$Points ~ learning14$Attitude + learning14$gender + learning14$Age)
summary(model)

# The model was significant, and explained 19 % of the variance in the DV. Positive learning attitudes
# contributed to a better efficiancy in points. Age and gender had no significant effects.

model <- lm(learning14$Points ~ learning14$Attitude + learning14$surf + learning14$stra + learning14$deep)
summary(model)

#I added the three learning styles to the model; none of them was significant. therefore I ran a final model, which include
#only attitude as explanatory variable. The model was significant, and explained 19% of the variance
#in the dependent variable, F(1, 164) = 38.61, p <.001. The unsrandardized regression coefficients of attitude was B=.35.
# This can be interpreted as more positive attitudes toward learning resultaed in higher points.

final_model <- lm(learning14$Points ~ learning14$Attitude)
summary(final_model)

#I created plots to diagnostize model fit. Theere seems to be some violaationn against normality in each plot.
par(mfrow = c(2,2))
plot(final_model, which = c(1, 2, 5))
```







My final model included only attitude as explanatory variable. The model was significant, and explained 19% of the variance in the dependent variable, F(1, 164) = 38.61, p <.001. The unstandardized regression coefficients of attitude was B=.35.
This can be interpreted as more positive attitudes toward learning resultaed in higher points. However, I created plots to diagnostize model fit. Theere seems to be some violaationn against normality in each plot.




